### ISSUE TITLE
Try Stepping sequence with LEDs

### ISSUE THREAD

**Issue by nikonoll** [nikonoll/steppingMotor#1]
- [x] Do simple LED representation of stepping sequence
- [x] Abstract Function for stepping for a certain amount of revolutions
- [x] Add reverse movements
- [x] Implement "revert to start position" functionality

**Comment by nikonoll** [comment]
http://www.elektronx.de/tutorials/schrittmotorsteuerung-mit-dem-raspberry-pi/

**Comment by LukasOtis** [comment]
Schaltplan für den Aufbau der LEDs, zum verbessern des verständisess und einfach Style

![4leds_control](https://cloud.githubusercontent.com/assets/18629758/14762427/2cdcbee0-097a-11e6-922a-e4db3cbe1548.JPG)

**Comment by LukasOtis** [comment]
Hab den Aufbau jetzt mal mit einem sehr unschönen Code getestet. Es läuft, die LEDs leuchten und alles in einem sehr sicheren bereich.
